using System;
using System.Collections.Generic;
using WCSharp.Api;
using static WCSharp.Api.Common;

namespace WCSharp.Events
{
	public static partial class PlayerUnitEvents
	{
		private static readonly Dictionary<int, playerunitevent> playerUnitEventNativesById = new()
		{
			{ (int)HeroEvent.BecomesRevivable, EVENT_PLAYER_HERO_REVIVABLE },
			{ (int)HeroEvent.CancelsRevive, EVENT_PLAYER_HERO_REVIVE_CANCEL },
			{ (int)HeroEvent.FinishesRevive, EVENT_PLAYER_HERO_REVIVE_FINISH },
			{ (int)HeroEvent.LearnsSpell, EVENT_PLAYER_HERO_SKILL },
			{ (int)HeroEvent.Levels, EVENT_PLAYER_HERO_LEVEL },
			{ (int)HeroEvent.StartsRevive, EVENT_PLAYER_HERO_REVIVE_START },
			{ (int)HeroTypeEvent.BecomesRevivable, EVENT_PLAYER_HERO_REVIVABLE },
			{ (int)HeroTypeEvent.CancelsRevive, EVENT_PLAYER_HERO_REVIVE_CANCEL },
			{ (int)HeroTypeEvent.FinishesRevive, EVENT_PLAYER_HERO_REVIVE_FINISH },
			{ (int)HeroTypeEvent.LearnsSpell, EVENT_PLAYER_HERO_SKILL },
			{ (int)HeroTypeEvent.Levels, EVENT_PLAYER_HERO_LEVEL },
			{ (int)HeroTypeEvent.StartsRevive, EVENT_PLAYER_HERO_REVIVE_START },
			{ (int)ItemEvent.IsAbsorbed, EVENT_PLAYER_UNIT_PICKUP_ITEM },
			{ (int)ItemEvent.IsDropped, EVENT_PLAYER_UNIT_DROP_ITEM },
			{ (int)ItemEvent.IsPawned, EVENT_PLAYER_UNIT_PAWN_ITEM },
			{ (int)ItemEvent.IsPickedUp, EVENT_PLAYER_UNIT_PICKUP_ITEM },
			{ (int)ItemEvent.IsSold, EVENT_PLAYER_UNIT_SELL_ITEM },
			{ (int)ItemEvent.IsStacked, EVENT_PLAYER_UNIT_STACK_ITEM },
			{ (int)ItemEvent.IsUsed, EVENT_PLAYER_UNIT_USE_ITEM },
			{ (int)ItemTypeEvent.IsAbsorbed, EVENT_PLAYER_UNIT_PICKUP_ITEM },
			{ (int)ItemTypeEvent.IsDropped, EVENT_PLAYER_UNIT_DROP_ITEM },
			{ (int)ItemTypeEvent.IsPawned, EVENT_PLAYER_UNIT_PAWN_ITEM },
			{ (int)ItemTypeEvent.IsPickedUp, EVENT_PLAYER_UNIT_PICKUP_ITEM },
			{ (int)ItemTypeEvent.IsSold, EVENT_PLAYER_UNIT_SELL_ITEM },
			{ (int)ItemTypeEvent.IsStacked, EVENT_PLAYER_UNIT_STACK_ITEM },
			{ (int)ItemTypeEvent.IsUsed, EVENT_PLAYER_UNIT_USE_ITEM },
			{ (int)PlayerEvent.DeselectsUnit, EVENT_PLAYER_UNIT_DESELECTED },
			{ (int)PlayerEvent.GainsOwnership, EVENT_PLAYER_UNIT_CHANGE_OWNER },
			{ (int)PlayerEvent.LosesOwnership, EVENT_PLAYER_UNIT_CHANGE_OWNER },
			{ (int)PlayerEvent.SelectsUnit, EVENT_PLAYER_UNIT_SELECTED },
			{ (int)ResearchEvent.IsCancelled, EVENT_PLAYER_UNIT_RESEARCH_CANCEL },
			{ (int)ResearchEvent.IsFinished, EVENT_PLAYER_UNIT_RESEARCH_FINISH },
			{ (int)ResearchEvent.IsStarted, EVENT_PLAYER_UNIT_RESEARCH_START },
			{ (int)SpellEvent.Cast, EVENT_PLAYER_UNIT_SPELL_CAST },
			{ (int)SpellEvent.Channel, EVENT_PLAYER_UNIT_SPELL_CHANNEL },
			{ (int)SpellEvent.Effect, EVENT_PLAYER_UNIT_SPELL_EFFECT },
			{ (int)SpellEvent.EndCast, EVENT_PLAYER_UNIT_SPELL_ENDCAST },
			{ (int)SpellEvent.Finish, EVENT_PLAYER_UNIT_SPELL_FINISH },
			{ (int)SpellEvent.Learned, EVENT_PLAYER_HERO_SKILL },
			{ (int)UnitEvent.Attacks, EVENT_PLAYER_UNIT_ATTACKED },
			{ (int)UnitEvent.BuysUnit, EVENT_PLAYER_UNIT_SELL },
			{ (int)UnitEvent.CancelsBeingConstructed, EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL },
			{ (int)UnitEvent.CancelsConstruction, EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL },
			{ (int)UnitEvent.CancelsResearch, EVENT_PLAYER_UNIT_RESEARCH_CANCEL },
			{ (int)UnitEvent.CancelsTraining, EVENT_PLAYER_UNIT_TRAIN_CANCEL },
			{ (int)UnitEvent.CancelsUpgrade, EVENT_PLAYER_UNIT_UPGRADE_CANCEL },
			{ (int)UnitEvent.ChangesOwner, EVENT_PLAYER_UNIT_CHANGE_OWNER },
			{ (int)UnitEvent.Damaging, EVENT_PLAYER_UNIT_DAMAGING },
			{ (int)UnitEvent.DamagingTaken, EVENT_PLAYER_UNIT_DAMAGING },
			{ (int)UnitEvent.Decays, EVENT_PLAYER_UNIT_DECAY },
			{ (int)UnitEvent.Dies, EVENT_PLAYER_UNIT_DEATH },
			{ (int)UnitEvent.DropsItem, EVENT_PLAYER_UNIT_DROP_ITEM },
			{ (int)UnitEvent.FinishesBeingConstructed, EVENT_PLAYER_UNIT_CONSTRUCT_FINISH },
			{ (int)UnitEvent.FinishesConstruction, EVENT_PLAYER_UNIT_CONSTRUCT_FINISH },
			{ (int)UnitEvent.FinishesResearch, EVENT_PLAYER_UNIT_RESEARCH_FINISH },
			{ (int)UnitEvent.FinishesTraining, EVENT_PLAYER_UNIT_TRAIN_FINISH },
			{ (int)UnitEvent.FinishesUpgrade, EVENT_PLAYER_UNIT_UPGRADE_FINISH },
			{ (int)UnitEvent.IsAttacked, EVENT_PLAYER_UNIT_ATTACKED },
			{ (int)UnitEvent.IsDamaged, EVENT_PLAYER_UNIT_DAMAGED },
			{ (int)UnitEvent.IsDamagedDealt, EVENT_PLAYER_UNIT_DAMAGED },
			{ (int)UnitEvent.IsDeselected, EVENT_PLAYER_UNIT_DESELECTED },
			{ (int)UnitEvent.IsDetected, EVENT_PLAYER_UNIT_DETECTED },
			{ (int)UnitEvent.IsHidden, EVENT_PLAYER_UNIT_HIDDEN },
			{ (int)UnitEvent.IsLoaded, EVENT_PLAYER_UNIT_LOADED },
			{ (int)UnitEvent.IsRescued, EVENT_PLAYER_UNIT_RESCUED },
			{ (int)UnitEvent.IsSelected, EVENT_PLAYER_UNIT_SELECTED },
			{ (int)UnitEvent.IsSold, EVENT_PLAYER_UNIT_SELL },
			{ (int)UnitEvent.Kills, EVENT_PLAYER_UNIT_DEATH },
			{ (int)UnitEvent.Loads, EVENT_PLAYER_UNIT_LOADED },
			{ (int)UnitEvent.PawnsItem, EVENT_PLAYER_UNIT_PAWN_ITEM },
			{ (int)UnitEvent.PicksUpItem, EVENT_PLAYER_UNIT_PICKUP_ITEM },
			{ (int)UnitEvent.ReceivesOrder, EVENT_PLAYER_UNIT_ISSUED_ORDER },
			{ (int)UnitEvent.ReceivesPointOrder, EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER },
			{ (int)UnitEvent.ReceivesTargetOrder, EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER },
			{ (int)UnitEvent.ReceivesUnitTypeOrder, EVENT_PLAYER_UNIT_ISSUED_UNIT_ORDER },
			{ (int)UnitEvent.Rescues, EVENT_PLAYER_UNIT_RESCUED },
			{ (int)UnitEvent.SellsItem, EVENT_PLAYER_UNIT_SELL_ITEM },
			{ (int)UnitEvent.SellsUnit, EVENT_PLAYER_UNIT_SELL },
			{ (int)UnitEvent.SpellCast, EVENT_PLAYER_UNIT_SPELL_CAST },
			{ (int)UnitEvent.SpellCastOn, EVENT_PLAYER_UNIT_SPELL_CAST },
			{ (int)UnitEvent.SpellChannel, EVENT_PLAYER_UNIT_SPELL_CHANNEL },
			{ (int)UnitEvent.SpellChannelOn, EVENT_PLAYER_UNIT_SPELL_CHANNEL },
			{ (int)UnitEvent.SpellEffect, EVENT_PLAYER_UNIT_SPELL_EFFECT },
			{ (int)UnitEvent.SpellEffectOn, EVENT_PLAYER_UNIT_SPELL_EFFECT },
			{ (int)UnitEvent.SpellEndCast, EVENT_PLAYER_UNIT_SPELL_ENDCAST },
			{ (int)UnitEvent.SpellEndCastOn, EVENT_PLAYER_UNIT_SPELL_ENDCAST },
			{ (int)UnitEvent.SpellFinish, EVENT_PLAYER_UNIT_SPELL_FINISH },
			{ (int)UnitEvent.SpellFinishOn, EVENT_PLAYER_UNIT_SPELL_FINISH },
			{ (int)UnitEvent.StacksItem, EVENT_PLAYER_UNIT_STACK_ITEM },
			{ (int)UnitEvent.StartsConstruction, EVENT_PLAYER_UNIT_CONSTRUCT_START },
			{ (int)UnitEvent.StartsResearch, EVENT_PLAYER_UNIT_RESEARCH_START },
			{ (int)UnitEvent.StartsTraining, EVENT_PLAYER_UNIT_TRAIN_START },
			{ (int)UnitEvent.StartsUpgrade, EVENT_PLAYER_UNIT_UPGRADE_START },
			{ (int)UnitEvent.Summons, EVENT_PLAYER_UNIT_SUMMON },
			{ (int)UnitEvent.UsesItem, EVENT_PLAYER_UNIT_USE_ITEM },
			{ (int)UnitTypeEvent.Attacks, EVENT_PLAYER_UNIT_ATTACKED },
			{ (int)UnitTypeEvent.BuysUnit, EVENT_PLAYER_UNIT_SELL },
			{ (int)UnitTypeEvent.CancelsBeingConstructed, EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL },
			{ (int)UnitTypeEvent.CancelsBeingTrained, EVENT_PLAYER_UNIT_TRAIN_CANCEL },
			{ (int)UnitTypeEvent.CancelsConstruction, EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL },
			{ (int)UnitTypeEvent.CancelsResearch, EVENT_PLAYER_UNIT_RESEARCH_CANCEL },
			{ (int)UnitTypeEvent.CancelsTraining, EVENT_PLAYER_UNIT_TRAIN_CANCEL },
			{ (int)UnitTypeEvent.CancelsUpgrade, EVENT_PLAYER_UNIT_UPGRADE_CANCEL },
			{ (int)UnitTypeEvent.ChangesOwner, EVENT_PLAYER_UNIT_CHANGE_OWNER },
			{ (int)UnitTypeEvent.Damaging, EVENT_PLAYER_UNIT_DAMAGING },
			{ (int)UnitTypeEvent.DamagingTaken, EVENT_PLAYER_UNIT_DAMAGING },
			{ (int)UnitTypeEvent.Decays, EVENT_PLAYER_UNIT_DECAY },
			{ (int)UnitTypeEvent.Dies, EVENT_PLAYER_UNIT_DEATH },
			{ (int)UnitTypeEvent.DropsItem, EVENT_PLAYER_UNIT_DROP_ITEM },
			{ (int)UnitTypeEvent.FinishesBeingConstructed, EVENT_PLAYER_UNIT_CONSTRUCT_FINISH },
			{ (int)UnitTypeEvent.FinishesBeingTrained, EVENT_PLAYER_UNIT_TRAIN_FINISH },
			{ (int)UnitTypeEvent.FinishesConstruction, EVENT_PLAYER_UNIT_CONSTRUCT_FINISH },
			{ (int)UnitTypeEvent.FinishesResearch, EVENT_PLAYER_UNIT_RESEARCH_FINISH },
			{ (int)UnitTypeEvent.FinishesTraining, EVENT_PLAYER_UNIT_TRAIN_FINISH },
			{ (int)UnitTypeEvent.FinishesUpgrade, EVENT_PLAYER_UNIT_UPGRADE_FINISH },
			{ (int)UnitTypeEvent.IsAttacked, EVENT_PLAYER_UNIT_ATTACKED },
			{ (int)UnitTypeEvent.IsDamaged, EVENT_PLAYER_UNIT_DAMAGED },
			{ (int)UnitTypeEvent.IsDamagedDealt, EVENT_PLAYER_UNIT_DAMAGED },
			{ (int)UnitTypeEvent.IsDeselected, EVENT_PLAYER_UNIT_DESELECTED },
			{ (int)UnitTypeEvent.IsDetected, EVENT_PLAYER_UNIT_DETECTED },
			{ (int)UnitTypeEvent.IsHidden, EVENT_PLAYER_UNIT_HIDDEN },
			{ (int)UnitTypeEvent.IsLoaded, EVENT_PLAYER_UNIT_LOADED },
			{ (int)UnitTypeEvent.IsRescued, EVENT_PLAYER_UNIT_RESCUED },
			{ (int)UnitTypeEvent.IsSelected, EVENT_PLAYER_UNIT_SELECTED },
			{ (int)UnitTypeEvent.IsSold, EVENT_PLAYER_UNIT_SELL },
			{ (int)UnitTypeEvent.IsSummoned, EVENT_PLAYER_UNIT_SUMMON },
			{ (int)UnitTypeEvent.Kills, EVENT_PLAYER_UNIT_DEATH },
			{ (int)UnitTypeEvent.Loads, EVENT_PLAYER_UNIT_LOADED },
			{ (int)UnitTypeEvent.PawnsItem, EVENT_PLAYER_UNIT_PAWN_ITEM },
			{ (int)UnitTypeEvent.PicksUpItem, EVENT_PLAYER_UNIT_PICKUP_ITEM },
			{ (int)UnitTypeEvent.ReceivesOrder, EVENT_PLAYER_UNIT_ISSUED_ORDER },
			{ (int)UnitTypeEvent.ReceivesPointOrder, EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER },
			{ (int)UnitTypeEvent.ReceivesTargetOrder, EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER },
			{ (int)UnitTypeEvent.ReceivesUnitTypeOrder, EVENT_PLAYER_UNIT_ISSUED_UNIT_ORDER },
			{ (int)UnitTypeEvent.Rescues, EVENT_PLAYER_UNIT_RESCUED },
			{ (int)UnitTypeEvent.SellsItem, EVENT_PLAYER_UNIT_SELL_ITEM },
			{ (int)UnitTypeEvent.SellsUnit, EVENT_PLAYER_UNIT_SELL },
			{ (int)UnitTypeEvent.SpellCast, EVENT_PLAYER_UNIT_SPELL_CAST },
			{ (int)UnitTypeEvent.SpellCastOn, EVENT_PLAYER_UNIT_SPELL_CAST },
			{ (int)UnitTypeEvent.SpellChannel, EVENT_PLAYER_UNIT_SPELL_CHANNEL },
			{ (int)UnitTypeEvent.SpellChannelOn, EVENT_PLAYER_UNIT_SPELL_CHANNEL },
			{ (int)UnitTypeEvent.SpellEffect, EVENT_PLAYER_UNIT_SPELL_EFFECT },
			{ (int)UnitTypeEvent.SpellEffectOn, EVENT_PLAYER_UNIT_SPELL_EFFECT },
			{ (int)UnitTypeEvent.SpellEndCast, EVENT_PLAYER_UNIT_SPELL_ENDCAST },
			{ (int)UnitTypeEvent.SpellEndCastOn, EVENT_PLAYER_UNIT_SPELL_ENDCAST },
			{ (int)UnitTypeEvent.SpellFinish, EVENT_PLAYER_UNIT_SPELL_FINISH },
			{ (int)UnitTypeEvent.SpellFinishOn, EVENT_PLAYER_UNIT_SPELL_FINISH },
			{ (int)UnitTypeEvent.StacksItem, EVENT_PLAYER_UNIT_STACK_ITEM },
			{ (int)UnitTypeEvent.StartsBeingConstructed, EVENT_PLAYER_UNIT_CONSTRUCT_START },
			{ (int)UnitTypeEvent.StartsBeingTrained, EVENT_PLAYER_UNIT_TRAIN_START },
			{ (int)UnitTypeEvent.StartsConstruction, EVENT_PLAYER_UNIT_CONSTRUCT_START },
			{ (int)UnitTypeEvent.StartsResearch, EVENT_PLAYER_UNIT_RESEARCH_START },
			{ (int)UnitTypeEvent.StartsTraining, EVENT_PLAYER_UNIT_TRAIN_START },
			{ (int)UnitTypeEvent.StartsUpgrade, EVENT_PLAYER_UNIT_UPGRADE_START },
			{ (int)UnitTypeEvent.Summons, EVENT_PLAYER_UNIT_SUMMON },
			{ (int)UnitTypeEvent.UsesItem, EVENT_PLAYER_UNIT_USE_ITEM },
		};
		private static readonly Dictionary<int, Func<int>> filterFuncIdsByEvent = new()
		{
			{ (int)HeroTypeEvent.BecomesRevivable, () => GetUnitTypeId(GetRevivableUnit()) },
			{ (int)HeroTypeEvent.CancelsRevive, () => GetUnitTypeId(GetRevivingUnit()) },
			{ (int)HeroTypeEvent.FinishesRevive, () => GetUnitTypeId(GetRevivingUnit()) },
			{ (int)HeroTypeEvent.LearnsSpell, () => GetUnitTypeId(GetLearningUnit()) },
			{ (int)HeroTypeEvent.Levels, () => GetUnitTypeId(GetLevelingUnit()) },
			{ (int)HeroTypeEvent.StartsRevive, () => GetUnitTypeId(GetRevivingUnit()) },
			{ (int)ItemTypeEvent.IsAbsorbed, () => GetItemTypeId(BlzGetAbsorbingItem()) },
			{ (int)ItemTypeEvent.IsDropped, () => GetItemTypeId(GetManipulatedItem()) },
			{ (int)ItemTypeEvent.IsPawned, () => GetItemTypeId(GetManipulatedItem()) },
			{ (int)ItemTypeEvent.IsPickedUp, () => GetItemTypeId(GetManipulatedItem()) },
			{ (int)ItemTypeEvent.IsSold, () => GetItemTypeId(GetSoldItem()) },
			{ (int)ItemTypeEvent.IsStacked, () => GetItemTypeId(GetManipulatedItem()) },
			{ (int)ItemTypeEvent.IsUsed, () => GetItemTypeId(GetManipulatedItem()) },
			{ (int)ResearchEvent.IsCancelled, () => GetResearched() },
			{ (int)ResearchEvent.IsFinished, () => GetResearched() },
			{ (int)ResearchEvent.IsStarted, () => GetResearched() },
			{ (int)SpellEvent.Cast, () => GetSpellAbilityId() },
			{ (int)SpellEvent.Channel, () => GetSpellAbilityId() },
			{ (int)SpellEvent.Effect, () => GetSpellAbilityId() },
			{ (int)SpellEvent.EndCast, () => GetSpellAbilityId() },
			{ (int)SpellEvent.Finish, () => GetSpellAbilityId() },
			{ (int)SpellEvent.Learned, () => GetLearnedSkill() },
			{ (int)UnitTypeEvent.Attacks, () => GetUnitTypeId(GetAttacker()) },
			{ (int)UnitTypeEvent.BuysUnit, () => GetUnitTypeId(GetBuyingUnit()) },
			{ (int)UnitTypeEvent.CancelsBeingConstructed, () => GetUnitTypeId(GetCancelledStructure()) },
			{ (int)UnitTypeEvent.CancelsBeingTrained, () => GetTrainedUnitType() },
			{ (int)UnitTypeEvent.CancelsConstruction, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.CancelsResearch, () => GetUnitTypeId(GetResearchingUnit()) },
			{ (int)UnitTypeEvent.CancelsTraining, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.CancelsUpgrade, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.ChangesOwner, () => GetUnitTypeId(GetChangingUnit()) },
			{ (int)UnitTypeEvent.Damaging, () => GetUnitTypeId(GetEventDamageSource()) },
			{ (int)UnitTypeEvent.DamagingTaken, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.Decays, () => GetUnitTypeId(GetDecayingUnit()) },
			{ (int)UnitTypeEvent.Dies, () => GetUnitTypeId(GetDyingUnit()) },
			{ (int)UnitTypeEvent.DropsItem, () => GetUnitTypeId(GetManipulatingUnit()) },
			{ (int)UnitTypeEvent.FinishesBeingConstructed, () => GetUnitTypeId(GetConstructedStructure()) },
			{ (int)UnitTypeEvent.FinishesBeingTrained, () => GetUnitTypeId(GetTrainedUnit()) },
			{ (int)UnitTypeEvent.FinishesConstruction, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.FinishesResearch, () => GetUnitTypeId(GetResearchingUnit()) },
			{ (int)UnitTypeEvent.FinishesTraining, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.FinishesUpgrade, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.IsAttacked, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.IsCreated, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.IsDamaged, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.IsDamagedDealt, () => GetUnitTypeId(GetEventDamageSource()) },
			{ (int)UnitTypeEvent.IsDeselected, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.IsDetected, () => GetUnitTypeId(GetDetectedUnit()) },
			{ (int)UnitTypeEvent.IsHidden, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.IsLoaded, () => GetUnitTypeId(GetLoadedUnit()) },
			{ (int)UnitTypeEvent.IsRemoved, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.IsRescued, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.IsSelected, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.IsSold, () => GetUnitTypeId(GetSoldUnit()) },
			{ (int)UnitTypeEvent.IsSummoned, () => GetUnitTypeId(GetSummonedUnit()) },
			{ (int)UnitTypeEvent.Kills, () => GetUnitTypeId(GetKillingUnit()) },
			{ (int)UnitTypeEvent.Loads, () => GetUnitTypeId(GetTransportUnit()) },
			{ (int)UnitTypeEvent.PawnsItem, () => GetUnitTypeId(GetManipulatingUnit()) },
			{ (int)UnitTypeEvent.PicksUpItem, () => GetUnitTypeId(GetManipulatingUnit()) },
			{ (int)UnitTypeEvent.ReceivesOrder, () => GetUnitTypeId(GetOrderedUnit()) },
			{ (int)UnitTypeEvent.ReceivesPointOrder, () => GetUnitTypeId(GetOrderedUnit()) },
			{ (int)UnitTypeEvent.ReceivesTargetOrder, () => GetUnitTypeId(GetOrderedUnit()) },
			{ (int)UnitTypeEvent.ReceivesUnitTypeOrder, () => GetUnitTypeId(GetOrderedUnit()) },
			{ (int)UnitTypeEvent.Rescues, () => GetUnitTypeId(GetRescuer()) },
			{ (int)UnitTypeEvent.SellsItem, () => GetUnitTypeId(GetSellingUnit()) },
			{ (int)UnitTypeEvent.SellsUnit, () => GetUnitTypeId(GetSellingUnit()) },
			{ (int)UnitTypeEvent.SpellCast, () => GetUnitTypeId(GetSpellAbilityUnit()) },
			{ (int)UnitTypeEvent.SpellCastOn, () => GetUnitTypeId(GetSpellAbilityUnit()) },
			{ (int)UnitTypeEvent.SpellChannel, () => GetUnitTypeId(GetSpellAbilityUnit()) },
			{ (int)UnitTypeEvent.SpellChannelOn, () => GetUnitTypeId(GetSpellAbilityUnit()) },
			{ (int)UnitTypeEvent.SpellEffect, () => GetUnitTypeId(GetSpellAbilityUnit()) },
			{ (int)UnitTypeEvent.SpellEffectOn, () => GetUnitTypeId(GetSpellAbilityUnit()) },
			{ (int)UnitTypeEvent.SpellEndCast, () => GetUnitTypeId(GetSpellAbilityUnit()) },
			{ (int)UnitTypeEvent.SpellEndCastOn, () => GetUnitTypeId(GetSpellAbilityUnit()) },
			{ (int)UnitTypeEvent.SpellFinish, () => GetUnitTypeId(GetSpellAbilityUnit()) },
			{ (int)UnitTypeEvent.SpellFinishOn, () => GetUnitTypeId(GetSpellAbilityUnit()) },
			{ (int)UnitTypeEvent.StacksItem, () => GetUnitTypeId(GetManipulatingUnit()) },
			{ (int)UnitTypeEvent.StartsBeingConstructed, () => GetUnitTypeId(GetConstructingStructure()) },
			{ (int)UnitTypeEvent.StartsBeingTrained, () => GetTrainedUnitType() },
			{ (int)UnitTypeEvent.StartsConstruction, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.StartsResearch, () => GetUnitTypeId(GetResearchingUnit()) },
			{ (int)UnitTypeEvent.StartsTraining, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.StartsUpgrade, () => GetUnitTypeId(GetTriggerUnit()) },
			{ (int)UnitTypeEvent.Summons, () => GetUnitTypeId(GetSummoningUnit()) },
			{ (int)UnitTypeEvent.UsesItem, () => GetUnitTypeId(GetManipulatingUnit()) },
		};
		private static readonly Dictionary<int, Func<handle>> filterFuncHandlesByEvent = new()
		{
			{ (int)HeroEvent.BecomesRevivable, () => GetRevivableUnit() },
			{ (int)HeroEvent.CancelsRevive, () => GetRevivingUnit() },
			{ (int)HeroEvent.FinishesRevive, () => GetRevivingUnit() },
			{ (int)HeroEvent.LearnsSpell, () => GetLearningUnit() },
			{ (int)HeroEvent.Levels, () => GetLevelingUnit() },
			{ (int)HeroEvent.StartsRevive, () => GetRevivingUnit() },
			{ (int)ItemEvent.IsAbsorbed, () => BlzGetAbsorbingItem() },
			{ (int)ItemEvent.IsDropped, () => GetManipulatedItem() },
			{ (int)ItemEvent.IsPawned, () => GetManipulatedItem() },
			{ (int)ItemEvent.IsPickedUp, () => GetManipulatedItem() },
			{ (int)ItemEvent.IsSold, () => GetSoldItem() },
			{ (int)ItemEvent.IsStacked, () => GetManipulatedItem() },
			{ (int)ItemEvent.IsUsed, () => GetManipulatedItem() },
			{ (int)PlayerEvent.DeselectsUnit, () => GetTriggerPlayer() },
			{ (int)PlayerEvent.GainsOwnership, () => GetOwningPlayer(GetTriggerUnit()) },
			{ (int)PlayerEvent.LosesOwnership, () => GetChangingUnitPrevOwner() },
			{ (int)PlayerEvent.SelectsUnit, () => GetTriggerPlayer() },
			{ (int)UnitEvent.Attacks, () => GetAttacker() },
			{ (int)UnitEvent.BuysUnit, () => GetBuyingUnit() },
			{ (int)UnitEvent.CancelsBeingConstructed, () => GetCancelledStructure() },
			{ (int)UnitEvent.CancelsConstruction, () => GetTriggerUnit() },
			{ (int)UnitEvent.CancelsResearch, () => GetResearchingUnit() },
			{ (int)UnitEvent.CancelsTraining, () => GetTriggerUnit() },
			{ (int)UnitEvent.CancelsUpgrade, () => GetTriggerUnit() },
			{ (int)UnitEvent.ChangesOwner, () => GetChangingUnit() },
			{ (int)UnitEvent.Damaging, () => GetEventDamageSource() },
			{ (int)UnitEvent.DamagingTaken, () => GetTriggerUnit() },
			{ (int)UnitEvent.Decays, () => GetDecayingUnit() },
			{ (int)UnitEvent.Dies, () => GetDyingUnit() },
			{ (int)UnitEvent.DropsItem, () => GetManipulatingUnit() },
			{ (int)UnitEvent.FinishesBeingConstructed, () => GetConstructedStructure() },
			{ (int)UnitEvent.FinishesConstruction, () => GetTriggerUnit() },
			{ (int)UnitEvent.FinishesResearch, () => GetResearchingUnit() },
			{ (int)UnitEvent.FinishesTraining, () => GetTriggerUnit() },
			{ (int)UnitEvent.FinishesUpgrade, () => GetTriggerUnit() },
			{ (int)UnitEvent.IsAttacked, () => GetTriggerUnit() },
			{ (int)UnitEvent.IsDamaged, () => GetTriggerUnit() },
			{ (int)UnitEvent.IsDamagedDealt, () => GetEventDamageSource() },
			{ (int)UnitEvent.IsDeselected, () => GetTriggerUnit() },
			{ (int)UnitEvent.IsDetected, () => GetDetectedUnit() },
			{ (int)UnitEvent.IsHidden, () => GetTriggerUnit() },
			{ (int)UnitEvent.IsLoaded, () => GetLoadedUnit() },
			{ (int)UnitEvent.IsRescued, () => GetTriggerUnit() },
			{ (int)UnitEvent.IsSelected, () => GetTriggerUnit() },
			{ (int)UnitEvent.IsSold, () => GetSoldUnit() },
			{ (int)UnitEvent.Kills, () => GetKillingUnit() },
			{ (int)UnitEvent.Loads, () => GetTransportUnit() },
			{ (int)UnitEvent.PawnsItem, () => GetManipulatingUnit() },
			{ (int)UnitEvent.PicksUpItem, () => GetManipulatingUnit() },
			{ (int)UnitEvent.ReceivesOrder, () => GetOrderedUnit() },
			{ (int)UnitEvent.ReceivesPointOrder, () => GetOrderedUnit() },
			{ (int)UnitEvent.ReceivesTargetOrder, () => GetOrderedUnit() },
			{ (int)UnitEvent.ReceivesUnitTypeOrder, () => GetOrderedUnit() },
			{ (int)UnitEvent.Rescues, () => GetRescuer() },
			{ (int)UnitEvent.SellsItem, () => GetSellingUnit() },
			{ (int)UnitEvent.SellsUnit, () => GetSellingUnit() },
			{ (int)UnitEvent.SpellCast, () => GetSpellAbilityUnit() },
			{ (int)UnitEvent.SpellCastOn, () => GetSpellAbilityUnit() },
			{ (int)UnitEvent.SpellChannel, () => GetSpellAbilityUnit() },
			{ (int)UnitEvent.SpellChannelOn, () => GetSpellAbilityUnit() },
			{ (int)UnitEvent.SpellEffect, () => GetSpellAbilityUnit() },
			{ (int)UnitEvent.SpellEffectOn, () => GetSpellAbilityUnit() },
			{ (int)UnitEvent.SpellEndCast, () => GetSpellAbilityUnit() },
			{ (int)UnitEvent.SpellEndCastOn, () => GetSpellAbilityUnit() },
			{ (int)UnitEvent.SpellFinish, () => GetSpellAbilityUnit() },
			{ (int)UnitEvent.SpellFinishOn, () => GetSpellAbilityUnit() },
			{ (int)UnitEvent.StacksItem, () => GetManipulatingUnit() },
			{ (int)UnitEvent.StartsConstruction, () => GetConstructingStructure() },
			{ (int)UnitEvent.StartsResearch, () => GetTriggerUnit() },
			{ (int)UnitEvent.StartsTraining, () => GetResearchingUnit() },
			{ (int)UnitEvent.StartsUpgrade, () => GetTriggerUnit() },
			{ (int)UnitEvent.Summons, () => GetSummoningUnit() },
			{ (int)UnitEvent.UsesItem, () => GetManipulatingUnit() },
		};
	}
}
