using WCSharp.Shared.Data;

/// <summary>
/// This class is auto-generated by WCSharp.ConstantGenerator.
/// </summary>
public static class Regions
{
	public static Rectangle Region_000 { get; set; } = new Rectangle(-288f, -416f, 480f, 576f);
	public static Rectangle Region_001 { get; set; } = new Rectangle(736f, -192f, 1216f, 640f);

}