name: Publish NuGet Package

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and publish to NuGet

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Create DefaultDocumentation directory
        run: |
          mkdir DefaultDocumentation

      - name: Add JassDoc documentation
        run: dotnet run --project ./Tools.JassDoc/Tools.JassDoc.csproj -- WCSharp.Api/WCSharp.Api.csproj

      - name: Restore dependencies
        run: dotnet restore

      - name: Build projects
        run: dotnet build --configuration Release --no-restore

      - name: Pack projects
        run: dotnet pack --configuration Release --no-build -o out /p:UsePackageReferences=true

      - name: Push to NuGet
        run: dotnet run --project ./Tools.NuGetPusher/Tools.NuGetPusher.csproj -- --ApiKey ${{ secrets.NUGET_API_KEY }} --PackageDirectory out
